# Generated by Django 2.1.4 on 2019-01-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('special', models.CharField(max_length=10)),
                ('effect', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasicCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('point', models.CharField(max_length=5)),
                ('pattern', models.CharField(choices=[('heart', '红桃'), ('spade', '黑桃'), ('diamond', '方块'), ('club', '梅花')], max_length=10)),
                ('special', models.CharField(blank=True, max_length=10)),
                ('effect', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DelayWisdomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('country', models.CharField(choices=[('wei', '魏'), ('shu', '蜀'), ('wu', '吴'), ('qun', '群'), ('jun', '君')], max_length=10)),
                ('nickname', models.CharField(max_length=50)),
                ('hp', models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5')])),
                ('skill', models.TextField()),
                ('united', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorseCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('point', models.CharField(max_length=5)),
                ('pattern', models.CharField(choices=[('heart', '红桃'), ('spade', '黑桃'), ('diamond', '方块'), ('club', '梅花')], max_length=10)),
                ('length', models.IntegerField()),
                ('effect', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImmedWisdomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasureCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('point', models.CharField(max_length=5)),
                ('pattern', models.CharField(choices=[('heart', '红桃'), ('spade', '黑桃'), ('diamond', '方块'), ('club', '梅花')], max_length=10)),
                ('effect', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PowerWisdomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('country', models.CharField(choices=[('wei', '魏'), ('shu', '蜀'), ('wu', '吴'), ('qun', '群'), ('jun', '君')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuseWisdomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('hide', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShieldCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('point', models.CharField(max_length=5)),
                ('pattern', models.CharField(choices=[('heart', '红桃'), ('spade', '黑桃'), ('diamond', '方块'), ('club', '梅花')], max_length=10)),
                ('effect', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('point', models.CharField(max_length=5)),
                ('pattern', models.CharField(choices=[('heart', '红桃'), ('spade', '黑桃'), ('diamond', '方块'), ('club', '梅花')], max_length=10)),
                ('length', models.IntegerField()),
                ('effect', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WisdomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('point', models.CharField(max_length=5)),
                ('pattern', models.CharField(choices=[('heart', '红桃'), ('spade', '黑桃'), ('diamond', '方块'), ('club', '梅花')], max_length=10)),
                ('effect', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rusewisdomcard',
            name='wisdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.WisdomCard'),
        ),
        migrations.AddField(
            model_name='powerwisdomcard',
            name='wisdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.WisdomCard'),
        ),
        migrations.AddField(
            model_name='immedwisdomcard',
            name='wisdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.WisdomCard'),
        ),
        migrations.AddField(
            model_name='delaywisdomcard',
            name='wisdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.WisdomCard'),
        ),
    ]
