# Generated by Django 2.1.5 on 2019-02-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_equipcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delaywisdomcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='delaywisdomcard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='delaywisdomcard',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='horsecard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='horsecard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='horsecard',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='immedwisdomcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='immedwisdomcard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='immedwisdomcard',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='measurecard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='measurecard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='measurecard',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='powerwisdomcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='powerwisdomcard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='powerwisdomcard',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='rusewisdomcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rusewisdomcard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='rusewisdomcard',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='shieldcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shieldcard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='shieldcard',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='weaponcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weaponcard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='weaponcard',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='badcard',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='basiccard',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='equipcard',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='herocard',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='wisdomcard',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
