# Generated by Django 2.1.4 on 2019-02-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20190216_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipcard',
            name='special',
            field=models.CharField(choices=[('immed', '非延时'), ('delay', '延时'), ('ruse', '诡计'), ('power', '势力')], default='weapon', max_length=20),
        ),
    ]
