# Generated by Django 2.1.5 on 2019-03-08 16:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_type'),
        ('cards', '0005_auto_20190220_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badcard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='basiccard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='equipcard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='herocard',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='wisdomcard',
            name='pic',
        ),
        migrations.AddField(
            model_name='badcard',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badcard',
            name='pid',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basiccard',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basiccard',
            name='pid',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipcard',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipcard',
            name='pid',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herocard',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herocard',
            name='pid',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wisdomcard',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wisdomcard',
            name='pid',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
