# Generated by Django 2.1.4 on 2019-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20190219_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipcard',
            name='special',
            field=models.CharField(choices=[('weapon', '武器'), ('horse', '坐骑'), ('shield', '防具'), ('measure', '宝物')], default='weapon', max_length=20),
        ),
    ]
