# Generated by Django 2.1.5 on 2019-03-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20190309_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badcard',
            name='pid',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='basiccard',
            name='pid',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='equipcard',
            name='pid',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='herocard',
            name='pid',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wisdomcard',
            name='pid',
            field=models.IntegerField(max_length=10),
        ),
    ]
