# Generated by Django 2.1.5 on 2019-03-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20190309_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badcard',
            name='pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basiccard',
            name='pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipcard',
            name='pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='herocard',
            name='pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wisdomcard',
            name='pid',
            field=models.IntegerField(),
        ),
    ]
