# Generated by Django 2.1.5 on 2019-02-19 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20190220_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='badcard',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 2, 19, 16, 30, 0, 275689, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basiccard',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 2, 19, 16, 30, 7, 941479, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipcard',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 2, 19, 16, 30, 12, 369541, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herocard',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 2, 19, 16, 30, 16, 790776, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wisdomcard',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 2, 19, 16, 30, 22, 686771, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
