# Generated by Django 2.1.4 on 2019-01-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('pw', models.CharField(max_length=256)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'female')], default=1)),
                ('ct_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'ordering': ['-ct_time'],
            },
        ),
    ]
