# Generated by Django 2.1.5 on 2019-03-08 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190217_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('article', 'article'), ('card', 'card')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
