# Generated by Django 2.1.4 on 2019-03-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pid', models.IntegerField()),
                ('special', models.CharField(max_length=10)),
                ('effect', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.CardBlog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasicCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pid', models.IntegerField()),
                ('point', models.CharField(max_length=5)),
                ('pattern', models.CharField(choices=[('heart', '红桃'), ('spade', '黑桃'), ('diamond', '方块'), ('club', '梅花')], max_length=10)),
                ('special', models.CharField(blank=True, max_length=10)),
                ('effect', models.TextField(blank=True, max_length=300)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.CardBlog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DelayWisdomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EquipCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pid', models.IntegerField()),
                ('special', models.CharField(choices=[('weapon', '武器'), ('horse', '坐骑'), ('shield', '防具'), ('measure', '宝物')], default='weapon', max_length=20)),
                ('point', models.CharField(max_length=5)),
                ('pattern', models.CharField(choices=[('heart', '红桃'), ('spade', '黑桃'), ('diamond', '方块'), ('club', '梅花')], max_length=10)),
                ('effect', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.CardBlog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pid', models.IntegerField()),
                ('country', models.CharField(choices=[('wei', '魏'), ('shu', '蜀'), ('wu', '吴'), ('qun', '群'), ('jun', '君')], max_length=10)),
                ('nickname', models.CharField(max_length=50)),
                ('hp', models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5')])),
                ('skill', models.TextField()),
                ('united', models.CharField(blank=True, max_length=30)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.CardBlog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorseCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(blank=True)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.EquipCard')),
            ],
        ),
        migrations.CreateModel(
            name='ImmedWisdomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useless', models.CharField(blank=True, default='', max_length=1)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.EquipCard')),
            ],
        ),
        migrations.CreateModel(
            name='PowerWisdomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('wei', '魏'), ('shu', '蜀'), ('wu', '吴'), ('qun', '群'), ('jun', '君')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RuseWisdomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShieldCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useless', models.CharField(blank=True, default='', max_length=1)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.EquipCard')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(blank=True)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.EquipCard')),
            ],
        ),
        migrations.CreateModel(
            name='WisdomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pid', models.IntegerField()),
                ('special', models.CharField(choices=[('immed', '非延时'), ('delay', '延时'), ('ruse', '诡计'), ('power', '势力')], default='immed', max_length=20)),
                ('point', models.CharField(max_length=5)),
                ('pattern', models.CharField(choices=[('heart', '红桃'), ('spade', '黑桃'), ('diamond', '方块'), ('club', '梅花')], max_length=10)),
                ('effect', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.CardBlog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rusewisdomcard',
            name='wisdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.WisdomCard'),
        ),
        migrations.AddField(
            model_name='powerwisdomcard',
            name='wisdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.WisdomCard'),
        ),
        migrations.AddField(
            model_name='immedwisdomcard',
            name='wisdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.WisdomCard'),
        ),
        migrations.AddField(
            model_name='delaywisdomcard',
            name='wisdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.WisdomCard'),
        ),
    ]
