# Generated by Django 2.1.4 on 2019-01-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisdomcard',
            name='special',
            field=models.CharField(choices=[('immed', '非延时'), ('delay', '延时'), ('ruse', '诡计'), ('power', '势力')], default='immed', max_length=20),
        ),
    ]
