# Generated by Django 2.1.5 on 2019-02-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horsecard',
            name='length',
        ),
        migrations.RemoveField(
            model_name='weaponcard',
            name='length',
        ),
    ]
