# Generated by Django 2.1.5 on 2019-02-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190220_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsecard',
            name='length',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weaponcard',
            name='length',
            field=models.IntegerField(default=1),
        ),
    ]
