# Generated by Django 2.1.5 on 2019-02-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20190220_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsecard',
            name='length',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='weaponcard',
            name='length',
            field=models.IntegerField(blank=True),
        ),
    ]
