# Generated by Django 2.1.5 on 2019-02-17 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20190216_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said', models.CharField(max_length=256)),
                ('said_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['said_time'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64, unique=True)),
                ('members', models.IntegerField(max_length=64)),
                ('ct_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ct_time'],
            },
        ),
        migrations.AddField(
            model_name='chats',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom.Room'),
        ),
        migrations.AddField(
            model_name='chats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserInfo'),
        ),
    ]
