# Generated by Django 2.1.5 on 2019-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.IntegerField(),
        ),
    ]
